### ISSUE TITLE
Bindings for 2.7.0

### ISSUE THREAD

**Issue by mevinDhun** [PSPDFKit/Xamarin-Android#2]
Hello, I have download the bindings and compile it using pspdfkit v2.7.0 but it throws errors while compiling the dll. It complains about some PSPDFViews missing. When will be the bindings be updated or where can i download the v2.6 aar file?

**Comment by steipete** [comment]
Thanks! We're already working on updated bindings. Usually takes  week or two after a release to get them updated. Can you paste in the error message you're getting, so we can verify that this is fixed in the next update?

**Comment by mevinDhun** [comment]
hi, below are some errors i get:
obj/Release/generated/src/PSPDFKit.UI.Search.PSPDFSearchViewInline.cs(9,121): error CS0234: The type or namespace name `PSPDFViews' does not exist in the namespace `PSPDFKit.UI'. Are you missing an assembly reference?
obj/Release/generated/src/PSPDFKit.UI.Search.PSPDFSearchViewModular.cs(9,122): error CS0234: The type or namespace name `PSPDFViews' does not exist in the namespace `PSPDFKit.UI'. Are you missing an assembly reference?
obj/Release/generated/src/Com.Pspdfkit.Document.Image.OnImagePickedListenerAdapter.cs(9,116): error CS0234: The type or namespace name `ImagePickerFragment' does not exist in the namespace `Com.Pspdfkit.Document.Image'. Are you missing an assembly reference?
obj/Release/generated/src/PSPDFKit.UI.PSPDFOutlineView.cs(9,98): error CS0234: The type or namespace name `PSPDFViews' does not exist in the namespace `PSPDFKit.UI'. Are you missing an assembly reference?
obj/Release/generated/src/PSPDFKit.UI.PSPDFThumbnailBar.cs(9,89): error CS0234: The type or namespace name `PSPDFViews' does not exist in the namespace `PSPDFKit.UI'. Are you missing an assembly reference?
obj/Release/generated/src/PSPDFKit.UI.Search.IPSPDFSearchView.cs(378,66): error CS0234: The type or namespace name `PSPDFViews' does not exist in the namespace `PSPDFKit.UI'. Are you missing an assembly reference?
obj/Release/generated/src/PSPDFKit.UI.Search.AbstractSearchView.cs(292,45): error CS0234: The type or namespace name `PSPDFViews' does not exist in the namespace `PSPDFKit.UI'. Are you missing an assembly reference?
obj/Release/generated/src/PSPDFKit.UI.Search.PSPDFSearchViewInline.cs(290,46): error CS0234: The type or namespace name `PSPDFViews' does not exist in the namespace `PSPDFKit.UI'. Are you missing an assembly reference?

**Comment by mevinDhun** [comment]
Update: I got the 2.6.1 android aar file from support and attempted to use the binding. I still get many errors during compilation:
![screen shot 2016-11-15 at 2 43 08 pm](https://cloud.githubusercontent.com/assets/17478561/20302814/3f570a52-ab42-11e6-89ce-7199cbd147d7.png)

**Comment by dalexsoto** [comment]
I will review 2.6.1 and let you know asap

**Comment by mevinDhun** [comment]
hello,
Any updates on this?

**Comment by dalexsoto** [comment]
Bindings are updated to latest PSPDFKit 2.8.1 please note that as of today you will need the following actions in your project to integrate the new binding

Set your app's **Target Framework** to Android 7.0 (API 24)

Set your Android Manifest **targetSdkVersion** to API 24 (Android 7.0)

**Remove and re add the following nugget packages in you App project**:
* https://www.nuget.org/packages/Xamarin.Android.Support.v4/25.0.1-rc1
* https://www.nuget.org/packages/Xamarin.Android.Support.v7.AppCompat/25.0.1-rc1
* https://www.nuget.org/packages/Xamarin.Android.Support.v7.RecyclerView/25.0.1-rc1
* https://www.nuget.org/packages/Xamarin.Android.Support.v7.CardView/25.0.1-rc1
* https://www.nuget.org/packages/Xamarin.Android.Support.Design/25.0.1-rc1

**Make sure you are using latest stable of Xamarin.Android 7 series**

**Comment by mevinDhun** [comment]
Hi,
I managed to build the dll but when i reference it in a new project, it is unable to compile:
`
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: Error: Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Xamarin.Android.Support.Fragment, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Xamarin.Android.Support.Fragment.dll'
  at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference, Mono.Cecil.ReaderParameters parameters) [0x0015d] in <c615bda75f884c7297065e705f6f110f>:0 
  at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference) [0x00001] in <c615bda75f884c7297065e705f6f110f>:0 
  at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences (System.Collections.Generic.ICollection`1[T] assemblies, Mono.Cecil.AssemblyDefinition assembly, System.Boolean topLevel) [0x00180] in <742ce926f1f848099e838fb951dcfe1c>:0 
  at Xamarin.Android.Tasks.ResolveAssemblies.Execute () [0x001ec] in <742ce926f1f848099e838fb951dcfe1c>:0  (pspdf.Droid)`

I tried adding the _Xamarin.Android.Support.Fragment_ nuget package but it is incompatible:
_Unable to resolve dependencies. 'Xamarin.Android.Support.Fragment 25.0.1-rc1' is not compatible with 'Xamarin.Android.Support.Design 25.0.1-rc1 constraint: Xamarin.Android.Support.Fragment (= 25.0.1-rc1)'._

**Comment by dalexsoto** [comment]
If you had older nuget references to the packages listed on my coment above please remove them all and re add them again using the prerelease version, if tou are using Xamarin.Forms in your project this will not work since Xamarin.Forms has hard dependencies to older support packages and PSPDFKit has to use the latest support library

**Comment by mevinDhun** [comment]
Hi,
I have tried it in a new xamarin forms project. Do you mean that Pspdfkit will not work with forms projects even with dependancy service?

**Comment by steipete** [comment]
Not yet - for that you'll need to wait a bit longer until Xamarin Forms has been updated to use the new Support Libraries.

**Comment by mevinDhun** [comment]
Ok thanks. Can you update this issue when PSPDFKit will be compatible with xamarin release?

**Comment by steipete** [comment]
This is something that needs to be fixed on Xamarin's side with updating their dependencies. We don't get a notification when this happens but please ping them as well.
